---
resources:
  - name: resource-tutorial
    type: git
    source:
      uri: https://github.com/fyamvbf/sandbox.git
      branch: main

jobs:
  - name: job-hello-world
    public: true
    serial: true
    plan:
      - get: resource-tutorial
        trigger: true
      - task: hello-world
        file: resource-tutorial/for_concourse_ci_tutorial/tutorials/basic/task-hello-world/task_hello_world.yml
